// Flat ESLint config for the SPA.
//
// Canonical workspace config (2026-05-17):
//   - typescript-eslint strictTypeChecked + stylisticTypeChecked
//     (type-aware rules; requires parserOptions.projectService = true)
//   - react-hooks recommended (rules-of-hooks + exhaustive-deps)
//   - react-refresh (only-export-components warning for HMR sanity)
//   - eslint-config-prettier last, to disable any rules that would
//     fight Prettier's formatting decisions
//
// NOTE: failOnWarnings (--max-warnings 0) is left for TS-3 after all
// existing warnings are resolved. pre-commit runs eslint --max-warnings 0
// already via the hook; this config file governs rule severity only.
//
// Stylistic rules are owned by Prettier (see .prettierrc.json), not ESLint.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import eslintConfigPrettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      // Generated by `make openapi-export` from the FastAPI schema —
      // never hand-edited, no value in linting it.
      "src/api/types.gen.ts",
    ],
  },
  js.configs.recommended,
  // strictTypeChecked supersedes recommended and adds type-aware rules.
  // stylisticTypeChecked adds stylistic type-aware rules (consistent-type-
  // imports, etc.) that Prettier doesn't cover.
  // Scoped to src/**/*.{ts,tsx} so type-aware rules don't fire on
  // postcss.config.js / vite.config.ts / other tooling JS files that are
  // not included in tsconfig.app.json.
  ...tseslint.configs.strictTypeChecked.map((c) => ({
    ...c,
    files: ["src/**/*.{ts,tsx}"],
  })),
  ...tseslint.configs.stylisticTypeChecked.map((c) => ({
    ...c,
    files: ["src/**/*.{ts,tsx}"],
  })),
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      parserOptions: {
        // Type-aware linting: resolve types from the project's tsconfig.
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: {
        ...globals.browser,
        // `process` shows up only in vite.config.ts / vitest.config.ts
        // (which read env), but globals.browser doesn't carry it; add
        // it for the tooling files we lint alongside src/.
        process: "readonly",
      },
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
      // Prefer the typescript-eslint variant, which understands
      // declaration merging and ambient types.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // no-explicit-any: `any` must be explicit and justified. Using
      // `unknown` + narrowing is almost always possible; allow `any` only
      // with an inline suppression and a comment explaining why.
      // NOTE: was "warn" pre-TS-3; promoted to "error" in TS-3.
      "@typescript-eslint/no-explicit-any": "error",
      // restrict-template-expressions fires on legitimate string
      // coercions in JSX (e.g. `${someNumber}`). Allow number|boolean.
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      // no-confusing-void-expression: too noisy with void-typed callbacks
      // passed inline (e.g. onClick={() => void someAsyncFn()}).
      "@typescript-eslint/no-confusing-void-expression": "off",
      // prefer-nullish-coalescing is stylistic; Prettier / existing
      // patterns already prefer || in guards; turn off to avoid churn.
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      // consistent-type-assertions: "as" is the project convention.
      "@typescript-eslint/consistent-type-assertions": [
        "error",
        { assertionStyle: "as" },
      ],
      // no-unnecessary-condition: after strict tsconfig flags, many
      // defensive patterns (optional chaining, nullish coalescing) are
      // flagged because TypeScript narrows types more aggressively.
      // Keep the rule but downgrade to warn so CI stays green while the
      // team works through them incrementally.
      "@typescript-eslint/no-unnecessary-condition": "warn",
      // no-non-null-assertion: needed post-noUncheckedIndexedAccess where
      // bounds are proven by loop/length checks. Warn rather than error in
      // src/ so CI catches new introductions without blocking fixes.
      "@typescript-eslint/no-non-null-assertion": "warn",
      // no-empty-function: empty stubs in test scaffolding are intentional.
      // Configured to "warn" to surface real empty functions in review.
      "@typescript-eslint/no-empty-function": "warn",
      // require-await: async functions without await exist as API-shape
      // adapters (satisfies an interface that requires async). Warn only.
      "@typescript-eslint/require-await": "warn",
      // no-misused-promises: event handlers often accept async callbacks.
      // Disable for JSX event handlers to allow the common pattern.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      // no-unsafe-*: window.__ENV__ is an untyped runtime injection; the
      // pattern is intentional. Disable at src/ level; re-enable after a
      // proper Vite `define` or `import.meta.env` migration (roadmap §18).
      "@typescript-eslint/no-unsafe-assignment": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
      "@typescript-eslint/no-unsafe-argument": "warn",
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-return": "warn",
    },
  },
  {
    files: ["src/**/*.test.{ts,tsx}", "src/test/**/*.{ts,tsx}"],
    languageOptions: {
      globals: {
        // Vitest globals are enabled in vitest.config.ts; mirror the
        // ones we actually use in tests.
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        vi: "readonly",
        // jsdom + node globals that creep into test scaffolding.
        global: "readonly",
        Buffer: "readonly",
      },
    },
    rules: {
      // Tests routinely cast around to satisfy mocks; loosen these
      // so the lint pass doesn't punish the test scaffolding.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-non-null-assertion": "off",
      // non-nullable-type-assertion-style fires when `as T` could be
      // replaced by `!`, but test files often cast to a specific subtype
      // (e.g. `as HTMLInputElement`) that also removes null — keep `as`.
      "@typescript-eslint/non-nullable-type-assertion-style": "off",
      // Tests legitimately grab prototype methods for monkey-patching
      // (e.g. beforeAll(() => { orig = HTMLElement.prototype.method })).
      "@typescript-eslint/unbound-method": "off",
      // Test files use `as` casts heavily for mock typing — allow.
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  // Must come last: turns off any stylistic ESLint rule that would
  // conflict with Prettier's formatting.
  eslintConfigPrettier,
);
