
const Card = ({title,sub,right,children,pad=true}) => (<div style={{background:'var(--bg-surface)',border:'1px solid var(--border-1)',borderRadius:8,overflow:'hidden'}}>{title?<div style={{padding:'12px 16px',borderBottom:'1px solid var(--border-1)',display:'flex',alignItems:'center',gap:10}}><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:'var(--ink-1)'}}>{title}</div>{sub?<div style={{marginTop:2,fontSize:11.5,color:'var(--ink-3)'}}>{sub}</div>:null}</div>{right||null}</div>:null}<div style={{padding:pad?'14px 16px':0}}>{children}</div></div>);
const Stat = ({label,value,tone='ink-1',sub}) => (<div style={{flex:1,background:'var(--bg-surface)',border:'1px solid var(--border-1)',borderRadius:8,padding:'14px 16px'}}><div className="mono" style={{fontSize:22,fontWeight:600,color:'var(--'+tone+')',letterSpacing:'-0.01em'}}>{value}</div><div style={{marginTop:4,fontSize:11,color:'var(--ink-3)',letterSpacing:'.04em',textTransform:'uppercase'}}>{label}</div>{sub?<div className="mono" style={{marginTop:2,fontSize:10.5,color:'var(--ink-4)'}}>{sub}</div>:null}</div>);
const Body = ({children,gap=14}) => (<div style={{padding:'20px 28px 28px',display:'flex',flexDirection:'column',gap}}>{children}</div>);
const Toggle2 = ({on}) => (<span style={{width:30,height:18,borderRadius:99,background:on?'var(--accent)':'var(--border-2)',position:'relative',display:'inline-block',flex:'0 0 auto'}}><span style={{position:'absolute',top:2,left:on?14:2,width:14,height:14,borderRadius:99,background:'#fff',boxShadow:'0 1px 2px rgba(0,0,0,.15)'}}/></span>);
const Seg = ({options,activeIdx=0}) => (<div style={{display:'inline-flex',padding:3,gap:2,background:'var(--bg-raised)',border:'1px solid var(--border-1)',borderRadius:7,flexWrap:'wrap'}}>{options.map((o,i)=>{const a=i===activeIdx;return <div key={o} style={{padding:'5px 12px',borderRadius:5,cursor:'pointer',background:a?'var(--bg-surface)':'transparent',boxShadow:a?'0 0 0 1px var(--border-1)':'none',color:a?'var(--ink-1)':'var(--ink-3)',fontSize:12,fontWeight:a?600:500}}>{o}</div>;})}</div>);
const SetRow = ({title,sub,children}) => (<div style={{display:'grid',gridTemplateColumns:'260px 1fr',gap:12,padding:'13px 16px',alignItems:'center',borderTop:'1px solid var(--border-1)'}}><div><div style={{fontSize:12.5,fontWeight:500,color:'var(--ink-1)'}}>{title}</div><div style={{marginTop:2,fontSize:11.5,color:'var(--ink-3)'}}>{sub}</div></div><div style={{display:'flex',justifyContent:'flex-end'}}>{children}</div></div>);
const Gate = ({ok,label,sub}) => (<div style={{borderRadius:10,border:'1px solid color-mix(in oklab, '+(ok?'var(--exact)':'var(--fuzzy)')+' 40%, var(--border-1))',background:'color-mix(in oklab, '+(ok?'var(--exact)':'var(--fuzzy)')+' 7%, var(--bg-surface))',padding:'14px 16px',display:'flex',alignItems:'center',gap:12}}><div style={{width:30,height:30,borderRadius:7,flex:'0 0 auto',background:'color-mix(in oklab, '+(ok?'var(--exact)':'var(--fuzzy)')+' 18%, var(--bg-surface))',color:ok?'var(--exact)':'var(--fuzzy)',display:'grid',placeItems:'center'}}><Icon name={ok?'checkCircle':'alert'} size={15}/></div><div style={{flex:1}}><div style={{fontSize:13.5,fontWeight:600,color:'var(--ink-1)'}}>{label}</div><div style={{marginTop:2,fontSize:12,color:'var(--ink-3)'}}>{sub}</div></div></div>);
const Tree = ({rows}) => (<div className="mono" style={{fontSize:11.5,lineHeight:1.9,color:'var(--ink-2)'}}>{rows.map((r,i)=>(<div key={i} style={{display:'flex',alignItems:'center',gap:8,paddingLeft:(r.d||0)*18}}>{r.dir?<Icon name="folder" size={12} style={{color:'var(--accent)'}}/>:<Icon name="file" size={12} style={{color:'var(--ink-4)'}}/>}<span style={{color:r.dir?'var(--ink-1)':'var(--ink-2)',fontWeight:r.dir?600:400}}>{r.name}</span><span style={{flex:1}}/>{r.meta?<span style={{color:'var(--ink-4)',fontSize:10.5}}>{r.meta}</span>:null}</div>))}</div>);
const Check = ({ok,label}) => (<div style={{display:'flex',alignItems:'center',gap:10,padding:'9px 0',borderTop:'1px solid var(--border-1)'}}><Icon name={ok?'checkCircle':'x'} size={15} style={{color:ok?'var(--exact)':'var(--mismatch)'}}/><span style={{flex:1,fontSize:12.5,color:'var(--ink-1)'}}>{label}</span></div>);

const BPMain = () => (<Body>
 <Gate ok={true} label="Package built · ready to submit" sub="Manifest (per-file checksums), the deterministic archive, metadata and a provenance README — the exact deliverable a PGDP project expects." />
 <div style={{display:'flex',gap:12}}><Stat label="deliverable" value="5 files"/><Stat label="manifest" value="1,229" sub="checksummed entries"/><Stat label="pipeline" value="v1.0" sub="25 stages"/><Stat label="pre-flight" value="passed" tone="exact"/></div>
 <div style={{display:'grid',gridTemplateColumns:'1.2fr 1fr',gap:14}}>
 <Card title="Deliverable" right={<Button variant="primary" size="sm" iconRight="arrowR">Continue to Submit check</Button>}><Tree rows={BP_TREE}/></Card>
 <Card title="manifest.json" sub="excerpt"><pre className="mono" style={{margin:0,fontSize:10.5,lineHeight:1.7,color:'var(--ink-2)',whiteSpace:'pre-wrap'}}>{`{
  "project": "belloc-survivals",
  "pages": 387,
  "canvas": "2480x3400",
  "built": "2026-06-02T00:00:00Z",
  "pipeline": "pd-prep v1.0",
  "files": 1229,
  "sha256": "a3f1…9c2"
}`}</pre></Card></div>
</Body>);
const BPSettings = () => (<Body><div><h2 style={{fontSize:16,fontWeight:600,color:'var(--ink-1)'}}>Stage settings · Build package</h2><div style={{marginTop:3,fontSize:12,color:'var(--ink-3)'}}>What goes in the manifest and deliverable.</div></div>
 <Card><SetRow title="Checksum algorithm" sub="Per-file integrity"><Seg options={['SHA-256','SHA-1','MD5']} activeIdx={0}/></SetRow><SetRow title="Include provenance README" sub="Pipeline + stage versions"><Toggle2 on={true}/></SetRow><SetRow title="Embed pipeline versions" sub="Record each stage's settings hash"><Toggle2 on={true}/></SetRow><SetRow title="Re-build package" sub="Rebuild manifest + deliverable"><Button variant="default" size="sm" icon="refresh">Re-build</Button></SetRow></Card></Body>);
Object.assign(window,{BPMain,BPSettings});
