/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects"];
        put?: never;
        /** Create Project */
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Project Config */
        patch: operations["update_project_config"];
        trace?: never;
    };
    "/api/data/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Project
         * @description Soft-delete: hide the project from default listings without removing data.
         *
         *     Idempotent — archiving an already-archived project is a no-op (still 200).
         */
        post: operations["archive_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/source-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Preview
         * @description Return image filenames + total count from the project's `source.zip`.
         *
         *     404s for unknown / wrong-owner projects (mirrors `assets.py`'s collapse
         *     of 403 → 404 to avoid leaking existence) and for the case where the
         *     presigned upload URL was issued but the PUT never landed.
         */
        get: operations["get_source_preview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/source-preview/{filename}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Preview Thumbnail
         * @description Return a JPEG thumbnail for one image entry inside the project's source.zip.
         *
         *     Pairs with ``GET /source-preview`` (slice 2): that route returns the
         *     image filenames; the SPA then issues one of these per filename to fill
         *     the preview strip. Auth/ownership match slice 2 verbatim — collapsing
         *     403 → 404 so existence isn't leaked.
         *
         *     Unknown filename and non-image filename both 404 (see
         *     ``extract_zip_image_thumbnail``); a corrupt image inside the zip
         *     becomes a 500 today, since that indicates a broken upload rather than
         *     a routine missing entry — let the SPA surface it.
         */
        get: operations["get_source_preview_thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unarchive Project
         * @description Restore a soft-deleted project. Idempotent.
         */
        post: operations["unarchive_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pages */
        get: operations["list_pages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/pages/{idx0}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Page */
        patch: operations["update_page"];
        trace?: never;
    };
    "/api/data/projects/{project_id}/pages/{idx0}/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Page Text */
        patch: operations["update_page_text"];
        trace?: never;
    };
    "/api/data/projects/{project_id}/pages/{idx0}/text/{suffix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Text */
        get: operations["get_page_text"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/pages/{idx0}/words": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Page Words
         * @description Hard-delete OCR words from a page's `<root>.words.json` and
         *     rewrite `<root>.txt` from the survivors (roadmap §9a).
         *
         *     v1 is intentionally a hard rewrite — the soft-delete-flag
         *     alternative is recorded in the roadmap as deferred. Unknown
         *     `word_ids` are silently skipped so the call is idempotent across
         *     retries; the response's `deleted_count` reports how many ids
         *     actually applied.
         */
        delete: operations["delete_page_words"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/system/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Defaults */
        get: operations["get_system_defaults"];
        /** Put System Defaults */
        put: operations["put_system_defaults"];
        post?: never;
        /**
         * Reset System Defaults
         * @description Reset the stored SystemDefaults to spec-08 defaults. Idempotent.
         */
        delete: operations["reset_system_defaults"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/system/defaults/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export System Defaults
         * @description Return the SystemDefaults as a downloadable JSON file.
         */
        get: operations["export_system_defaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/system/defaults/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import System Defaults
         * @description Replace the stored SystemDefaults with an imported JSON document.
         *
         *     Behaves like PUT — sharing the response shape so the frontend can
         *     `setDraft(response)` and the next GET will agree.
         */
        post: operations["import_system_defaults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Upload Url */
        post: operations["get_asset_upload_url"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/projects/{project_id}/assets/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Download Url */
        get: operations["get_asset_download_url"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recent Jobs */
        get: operations["list_recent_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["start_ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/process-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Page */
        post: operations["process_page"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/run-ocr-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Ocr Page */
        post: operations["run_ocr_page"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/suggest-splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Splits */
        post: operations["suggest_splits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/suggest-illustrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Illustrations */
        post: operations["suggest_illustrations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/extract-illustration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extract Illustration */
        post: operations["extract_illustration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Batch Job */
        post: operations["submit_batch_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_gpu_job"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_gpu_job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job
         * @description Create a fresh copy of a failed/cancelled job in `queued` status.
         *
         *     Same project_id and type — fresh id and timestamps. The original job
         *     stays in the database so the user can compare. The new job's payload
         *     starts as a copy of the original's; if `body.payload_override` is
         *     provided (P3 #16), its keys are shallow-merged over the original
         *     payload (override keys replace, others are preserved). Pass `None` /
         *     omit the body to retry verbatim.
         */
        post: operations["retry_gpu_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gpu/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description SSE — push status transitions until the job is terminal.
         *
         *     Subscribes to the in-process `JobEventBroker` and forwards events as
         *     `text/event-stream` frames. First frame is the current snapshot from
         *     the database so a late subscriber sees state immediately; subsequent
         *     frames come from the broker (zero-poll).
         */
        get: operations["stream_gpu_job_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cdn/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Cdn Put
         * @description Write `key` (under the data root) using bytes from the request body.
         *
         *     Path traversal (`..`, absolute paths) is rejected by the storage adapter.
         */
        put: operations["upload_cdn_asset"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlignmentOverride
         * @enum {string}
         */
        AlignmentOverride: "default" | "top" | "center" | "bottom";
        /** BatchJobRequest */
        BatchJobRequest: {
            /** Project Id */
            project_id: string;
            /**
             * Job Type
             * @enum {string}
             */
            job_type: "batch_process_pages" | "batch_ocr" | "batch_text_postprocess" | "batch_extract_illustrations" | "build_package";
            /** Page Idxs */
            page_idxs?: number[] | null;
        };
        /** BatchJobResponse */
        BatchJobResponse: {
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Estimated Pages
             * @default 0
             */
            estimated_pages: number;
            /**
             * Dispatch Mode
             * @default immediate
             * @enum {string}
             */
            dispatch_mode: "immediate" | "scheduled";
            /** Next Dispatch At */
            next_dispatch_at?: string | null;
        };
        /** BoundingBox */
        BoundingBox: {
            /** Left */
            left: number;
            /** Top */
            top: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "zip" | "s3_folder" | "local_folder";
            /** Source Uri */
            source_uri?: string | null;
        };
        /** CreateProjectResponse */
        CreateProjectResponse: {
            project: components["schemas"]["Project"];
            /** Upload Url */
            upload_url?: string | null;
            /** Upload Key */
            upload_key?: string | null;
        };
        /** DeleteWordsRequest */
        DeleteWordsRequest: {
            /** Split Suffix */
            split_suffix?: string | null;
            /** Word Ids */
            word_ids: string[];
        };
        /** DeleteWordsResponse */
        DeleteWordsResponse: {
            /** Text Key */
            text_key: string;
            /** Words Key */
            words_key: string;
            /** Deleted Count */
            deleted_count: number;
            /** Remaining Words */
            remaining_words: components["schemas"]["OcrWord"][];
            /** Text */
            text: string;
        };
        /** DownloadUrlResponse */
        DownloadUrlResponse: {
            /** Download Url */
            download_url: string;
            /**
             * Expires In
             * @default 3600
             */
            expires_in: number;
        };
        /** ExtractIllustrationRequest */
        ExtractIllustrationRequest: {
            /** Project Id */
            project_id: string;
            /** Idx0 */
            idx0: number;
            /** Region Index */
            region_index: number;
            /**
             * Output Format
             * @default jpg
             * @enum {string}
             */
            output_format: "jpg" | "png";
        };
        /** ExtractIllustrationResponse */
        ExtractIllustrationResponse: {
            /** Image Key */
            image_key: string;
            /** Image Url */
            image_url: string;
        };
        /** GetPageTextResponse */
        GetPageTextResponse: {
            /** Text */
            text: string;
            /** Text Key */
            text_key: string;
            /**
             * Words
             * @default []
             */
            words: components["schemas"]["OcrWord"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IllustrationRegion
         * @description Coords in SOURCE image space (original scan, pre-processing).
         */
        IllustrationRegion: {
            /**
             * Index
             * @default 1
             */
            index: number;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Type
             * @default illustration
             * @enum {string}
             */
            type: "illustration" | "decoration" | "plate";
            /** L */
            L?: number | null;
            /** R */
            R?: number | null;
            /** T */
            T?: number | null;
            /** B */
            B?: number | null;
            /**
             * Output Format
             * @default jpg
             * @enum {string}
             */
            output_format: "jpg" | "png";
            /**
             * Jpeg Quality
             * @default 85
             */
            jpeg_quality: number;
            /**
             * Convert To Grayscale
             * @default false
             */
            convert_to_grayscale: boolean;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Project Id */
            project_id: string;
            /** Source Key */
            source_key: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "zip" | "s3_folder" | "local_folder";
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Owner Id
             * @default default
             */
            owner_id: string;
            type: components["schemas"]["JobType"];
            /** @default queued */
            status: components["schemas"]["JobStatus"];
            progress?: components["schemas"]["JobProgress"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Next Dispatch At */
            next_dispatch_at?: string | null;
            /** Error Message */
            error_message?: string | null;
            /**
             * Gpu Backend
             * @default local
             * @enum {string}
             */
            gpu_backend: "local" | "cpu" | "modal" | "shared_container";
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
        };
        /** JobProgress */
        JobProgress: {
            /**
             * Current
             * @default 0
             */
            current: number;
            /**
             * Total
             * @default 0
             */
            total: number;
            /** Current Page */
            current_page?: number | null;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** JobResponse */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running";
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "scheduled" | "running" | "complete" | "error" | "cancelled";
        /**
         * JobType
         * @enum {string}
         */
        JobType: "unzip" | "thumbnails" | "batch_process_pages" | "batch_ocr" | "batch_text_postprocess" | "batch_extract_illustrations" | "build_package";
        /** ListPagesResponse */
        ListPagesResponse: {
            /** Pages */
            pages: components["schemas"]["PageRecord"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total: number;
        };
        /** OcrPageRequest */
        OcrPageRequest: {
            /** Project Id */
            project_id: string;
            /** Idx0 */
            idx0: number;
            /** Split Suffix */
            split_suffix?: string | null;
            /** Engine */
            engine?: ("doctr" | "tesseract") | null;
            /** Model Key */
            model_key?: string | null;
            /**
             * Batch Mode
             * @default false
             */
            batch_mode: boolean;
        };
        /** OcrPageResponse */
        OcrPageResponse: {
            /** Text */
            text: string;
            /** Words */
            words?: components["schemas"]["OcrWord"][];
            /** Text Key */
            text_key: string;
        };
        /** OcrWord */
        OcrWord: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Confidence */
            confidence: number;
            bounding_box: components["schemas"]["BoundingBox"];
            /** Split Suffix */
            split_suffix?: string | null;
        };
        /**
         * PageConfigOverrides
         * @description Per-page processing overrides. Every field None = inherit.
         */
        PageConfigOverrides: {
            /** Initial Crop */
            initial_crop?: [
                number,
                number,
                number,
                number
            ] | null;
            /** White Space Additional */
            white_space_additional?: [
                number,
                number,
                number,
                number
            ] | null;
            /** Threshold Level */
            threshold_level?: number | null;
            /** Fuzzy Pct */
            fuzzy_pct?: number | null;
            /** Pixel Count Columns */
            pixel_count_columns?: number | null;
            /** Pixel Count Rows */
            pixel_count_rows?: number | null;
            /** Skip Auto Deskew */
            skip_auto_deskew?: boolean | null;
            /** Deskew Before Crop */
            deskew_before_crop?: number | null;
            /** Deskew After Crop */
            deskew_after_crop?: number | null;
            /** Do Morph */
            do_morph?: boolean | null;
            /** Skip Denoise */
            skip_denoise?: boolean | null;
            /** Use Ocr Bbox Edge */
            use_ocr_bbox_edge?: boolean | null;
            /** Rotated Standard */
            rotated_standard?: boolean | null;
            /** Single Dimension Rescale */
            single_dimension_rescale?: boolean | null;
        };
        /**
         * PageOutput
         * @description One per split, or one for whole page.
         */
        PageOutput: {
            /** Full Prefix */
            full_prefix: string;
            /** Split Suffix */
            split_suffix: string | null;
            /** Reading Order */
            reading_order: number;
            /** Proofing Image Key */
            proofing_image_key?: string | null;
            /** Pre Ocr Image Key */
            pre_ocr_image_key?: string | null;
            /** Ocr Image Key */
            ocr_image_key?: string | null;
            /** Ocr Text Key */
            ocr_text_key?: string | null;
            /** For Zip Image Key */
            for_zip_image_key?: string | null;
            /** For Zip Text Key */
            for_zip_text_key?: string | null;
            /** @default pending */
            ocr_status: components["schemas"]["PageProcessingStatus"];
            /** Ocr Job Id */
            ocr_job_id?: string | null;
            /** Ocr Error */
            ocr_error?: string | null;
        };
        /**
         * PageProcessingStatus
         * @enum {string}
         */
        PageProcessingStatus: "pending" | "processing" | "complete" | "error";
        /** PageRecord */
        PageRecord: {
            /** Project Id */
            project_id: string;
            /** Idx0 */
            idx0: number;
            /** Prefix */
            prefix: string;
            /** Source Stem */
            source_stem: string;
            /**
             * Ignore
             * @default false
             */
            ignore: boolean;
            /** @default normal */
            page_type: components["schemas"]["PageType"];
            /** @default default */
            alignment: components["schemas"]["AlignmentOverride"];
            config_overrides?: components["schemas"]["PageConfigOverrides"];
            /** Splits */
            splits?: components["schemas"]["PageSplit"][];
            /** Illustration Regions */
            illustration_regions?: components["schemas"]["IllustrationRegion"][];
            /** Source Key */
            source_key?: string | null;
            /** Thumbnail Key */
            thumbnail_key?: string | null;
            /** Processed Image Key */
            processed_image_key?: string | null;
            /** Ocr Image Key */
            ocr_image_key?: string | null;
            /** @default pending */
            processing_status: components["schemas"]["PageProcessingStatus"];
            /** Processing Job Id */
            processing_job_id?: string | null;
            /** Processing Error */
            processing_error?: string | null;
            /** Last Processed At */
            last_processed_at?: string | null;
            /** Outputs */
            outputs?: components["schemas"]["PageOutput"][];
        };
        /**
         * PageSplit
         * @description Replaces the notebook's `PageSectionSplit`. Coords in PROCESSED image space.
         */
        PageSplit: {
            /** Suffix */
            suffix: string;
            /** Reading Order */
            reading_order: number;
            /** L */
            L?: number | null;
            /** R */
            R?: number | null;
            /** T */
            T?: number | null;
            /** B */
            B?: number | null;
            /**
             * Scale To Standard Page
             * @default true
             */
            scale_to_standard_page: boolean;
            alignment?: components["schemas"]["AlignmentOverride"] | null;
            /** Ocr Engine */
            ocr_engine?: ("doctr" | "tesseract") | null;
        };
        /**
         * PageType
         * @enum {string}
         */
        PageType: "normal" | "blank" | "plate_b" | "plate_p" | "plate_r";
        /** PipelineState */
        PipelineState: {
            /** Steps */
            steps?: {
                [key: string]: components["schemas"]["StepState"];
            };
        };
        /** ProcessPageRequest */
        ProcessPageRequest: {
            /** Project Id */
            project_id: string;
            /** Idx0 */
            idx0: number;
            config_overrides: components["schemas"]["PageConfigOverrides"];
            /**
             * Output Context
             * @default workbench
             * @enum {string}
             */
            output_context: "workbench" | "commit";
        };
        /** ProcessPageResponse */
        ProcessPageResponse: {
            /** Processed Image Key */
            processed_image_key: string;
            /** Processed Image Url */
            processed_image_url: string;
            /** Dimensions */
            dimensions: [
                number,
                number
            ];
            /** Processing Time Ms */
            processing_time_ms: number;
            /**
             * Backend
             * @enum {string}
             */
            backend: "local" | "cpu" | "mps" | "modal" | "shared_container";
            /**
             * Cold Start Ms
             * @default 0
             */
            cold_start_ms: number;
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /**
             * Owner Id
             * @default default
             */
            owner_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            status: components["schemas"]["ProjectStatus"];
            /** Page Count */
            page_count: number;
            /** Proof Page Count */
            proof_page_count: number;
            config: components["schemas"]["ProjectConfig"];
            pipeline_state: components["schemas"]["PipelineState"];
            /** Storage Prefix */
            storage_prefix: string;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
        };
        /** ProjectConfig */
        ProjectConfig: {
            /** Book Name */
            book_name: string;
            /** Source Uri */
            source_uri: string;
            /**
             * Proof Start Idx0
             * @default 0
             */
            proof_start_idx0: number;
            /**
             * Proof End Idx0
             * @default 0
             */
            proof_end_idx0: number;
            /** Cover Idx0 */
            cover_idx0?: number | null;
            /** Title Idx0 */
            title_idx0?: number | null;
            /**
             * Frontmatter Start Idx0
             * @default 0
             */
            frontmatter_start_idx0: number;
            /**
             * Frontmatter End Idx0
             * @default 0
             */
            frontmatter_end_idx0: number;
            /**
             * Bodymatter Start Idx0
             * @default 0
             */
            bodymatter_start_idx0: number;
            /**
             * Bodymatter End Idx0
             * @default 0
             */
            bodymatter_end_idx0: number;
            /**
             * Frontmatter Page Nbr Start
             * @default 1
             */
            frontmatter_page_nbr_start: number;
            /**
             * Bodymatter Page Nbr Start
             * @default 1
             */
            bodymatter_page_nbr_start: number;
            /**
             * Initial Crop All
             * @default [
             *       0,
             *       0,
             *       0,
             *       0
             *     ]
             */
            initial_crop_all: [
                number,
                number,
                number,
                number
            ];
            /**
             * Ocr Crop Top
             * @default 0
             */
            ocr_crop_top: number;
            /**
             * Ocr Crop Bottom
             * @default 0
             */
            ocr_crop_bottom: number;
            /**
             * Ocr Crop Left
             * @default 0
             */
            ocr_crop_left: number;
            /**
             * Ocr Crop Right
             * @default 0
             */
            ocr_crop_right: number;
            /** Custom Regex Passes */
            custom_regex_passes?: [
                string,
                string
            ][];
            /** Custom Scannos */
            custom_scannos?: {
                [key: string]: string;
            };
            /** Layout Category Overrides */
            layout_category_overrides?: {
                [key: string]: string | null;
            };
            /** Default Overrides */
            default_overrides?: {
                [key: string]: unknown;
            };
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "ingesting" | "configuring" | "processing" | "reviewing" | "packaging" | "complete";
        /**
         * RetryJobRequest
         * @description Optional body for `POST /api/gpu/jobs/{id}/retry`.
         *
         *     `payload_override`, when non-null, is shallow-merged over the original
         *     job's payload — keys present in the override replace the corresponding
         *     keys; keys not present are preserved from the original. The original
         *     job is never mutated, so the audit trail stays intact.
         */
        RetryJobRequest: {
            /** Payload Override */
            payload_override?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SourcePreviewResponse
         * @description Cheap-to-compute preview of an uploaded source zip (P2 #8).
         *
         *     Lets the SPA render a thumbnail strip / sanity-check the upload before
         *     triggering ingest. Backed by `peek_zip_image_names`, which only reads
         *     the zip's central directory — no per-entry decompression.
         */
        SourcePreviewResponse: {
            /** Filenames */
            filenames: string[];
            /** Total Image Count */
            total_image_count: number;
        };
        /** StepState */
        StepState: {
            /** @default pending */
            status: components["schemas"]["StepStatus"];
            /** Pages Complete */
            pages_complete?: number[];
            /** Pages Error */
            pages_error?: {
                [key: string]: string;
            };
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Job Id */
            job_id?: string | null;
        };
        /**
         * StepStatus
         * @enum {string}
         */
        StepStatus: "pending" | "running" | "complete" | "error";
        /** SuggestIllustrationsRequest */
        SuggestIllustrationsRequest: {
            /** Project Id */
            project_id: string;
            /** Idx0 */
            idx0: number;
        };
        /** SuggestIllustrationsResponse */
        SuggestIllustrationsResponse: {
            /**
             * Regions
             * @default []
             */
            regions: components["schemas"]["IllustrationRegion"][];
        };
        /** SuggestSplitsRequest */
        SuggestSplitsRequest: {
            /** Project Id */
            project_id: string;
            /** Idx0 */
            idx0: number;
        };
        /** SuggestSplitsResponse */
        SuggestSplitsResponse: {
            /**
             * Splits
             * @default []
             */
            splits: components["schemas"]["PageSplit"][];
        };
        /** SystemDefaults */
        SystemDefaults: {
            /**
             * Text Threshold
             * @default 140
             */
            text_threshold: number;
            /**
             * Page H W Ratio
             * @default 1.65
             */
            page_h_w_ratio: number;
            /**
             * Default Fuzzy Pct
             * @default 0.02
             */
            default_fuzzy_pct: number;
            /**
             * Default Pixel Count Columns
             * @default 150
             */
            default_pixel_count_columns: number;
            /**
             * Default Pixel Count Rows
             * @default 75
             */
            default_pixel_count_rows: number;
            /**
             * Ocr Engine
             * @default doctr
             * @enum {string}
             */
            ocr_engine: "doctr" | "tesseract";
            /** Ocr Model Key */
            ocr_model_key?: string | null;
            /**
             * Ocr Dpi
             * @default 150
             */
            ocr_dpi: number;
            /**
             * Ocr Bbox Edge Min Words
             * @default 5
             */
            ocr_bbox_edge_min_words: number;
            /**
             * Layout Detector
             * @default pp-doclayout-plus-l
             * @enum {string}
             */
            layout_detector: "none" | "contour" | "pp-doclayout-plus-l";
            /**
             * Layout Detector Confidence
             * @default 0.5
             */
            layout_detector_confidence: number;
            /** Layout Checkpoint */
            layout_checkpoint?: string | null;
            /** Standard Scannos */
            standard_scannos?: {
                [key: string]: string;
            };
            /** Hyphenation Join List */
            hyphenation_join_list?: string[];
        };
        /** UpdateConfigRequest */
        UpdateConfigRequest: {
            /** Project Config */
            project_config: {
                [key: string]: unknown;
            };
            /** Name */
            name?: string | null;
        };
        /** UpdateConfigResponse */
        UpdateConfigResponse: {
            project_config: components["schemas"]["ProjectConfig"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UpdatePageRequest */
        UpdatePageRequest: {
            page_type?: components["schemas"]["PageType"] | null;
            alignment?: components["schemas"]["AlignmentOverride"] | null;
            config_overrides?: components["schemas"]["PageConfigOverrides"] | null;
            /** Splits */
            splits?: components["schemas"]["PageSplit"][] | null;
            /** Illustration Regions */
            illustration_regions?: components["schemas"]["IllustrationRegion"][] | null;
        };
        /** UpdatePageTextRequest */
        UpdatePageTextRequest: {
            /** Split Suffix */
            split_suffix?: string | null;
            /** Text */
            text: string;
        };
        /** UpdatePageTextResponse */
        UpdatePageTextResponse: {
            /** Text Key */
            text_key: string;
        };
        /** UploadUrlRequest */
        UploadUrlRequest: {
            /** Key */
            key: string;
            /** Content Type */
            content_type: string;
        };
        /** UploadUrlResponse */
        UploadUrlResponse: {
            /** Upload Url */
            upload_url: string;
            /**
             * Expires In
             * @default 3600
             */
            expires_in: number;
        };
        /** UserContext */
        UserContext: {
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserContext"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_preview: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcePreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_preview_thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG thumbnail bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Project, source.zip, or named entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_project: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pages: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                page_type?: components["schemas"]["PageType"] | null;
                has_splits?: boolean | null;
                status?: components["schemas"]["PageProcessingStatus"] | null;
                review_needed?: boolean | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListPagesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                idx0: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_page: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                idx0: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_page_text: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                idx0: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePageTextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePageTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_text: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                idx0: number;
                suffix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPageTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_page_words: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                idx0: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteWordsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteWordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDefaults"];
                };
            };
        };
    };
    put_system_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemDefaults"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDefaults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_system_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDefaults"];
                };
            };
        };
    };
    export_system_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    import_system_defaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemDefaults"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemDefaults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_upload_url: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_asset_download_url: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_jobs: {
        parameters: {
            query?: {
                limit?: number;
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_ingest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessPageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ocr_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OcrPageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcrPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_splits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestSplitsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestSplitsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_illustrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestIllustrationsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestIllustrationsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_illustration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractIllustrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractIllustrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_batch_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_gpu_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_gpu_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_gpu_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RetryJobRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_gpu_job_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_cdn_asset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
