
const Card = ({title,sub,right,children,pad=true}) => (<div style={{background:'var(--bg-surface)',border:'1px solid var(--border-1)',borderRadius:8,overflow:'hidden'}}>{title?<div style={{padding:'12px 16px',borderBottom:'1px solid var(--border-1)',display:'flex',alignItems:'center',gap:10}}><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:'var(--ink-1)'}}>{title}</div>{sub?<div style={{marginTop:2,fontSize:11.5,color:'var(--ink-3)'}}>{sub}</div>:null}</div>{right||null}</div>:null}<div style={{padding:pad?'14px 16px':0}}>{children}</div></div>);
const Stat = ({label,value,tone='ink-1',sub}) => (<div style={{flex:1,background:'var(--bg-surface)',border:'1px solid var(--border-1)',borderRadius:8,padding:'14px 16px'}}><div className="mono" style={{fontSize:22,fontWeight:600,color:'var(--'+tone+')',letterSpacing:'-0.01em'}}>{value}</div><div style={{marginTop:4,fontSize:11,color:'var(--ink-3)',letterSpacing:'.04em',textTransform:'uppercase'}}>{label}</div>{sub?<div className="mono" style={{marginTop:2,fontSize:10.5,color:'var(--ink-4)'}}>{sub}</div>:null}</div>);
const Body = ({children,gap=14}) => (<div style={{padding:'20px 28px 28px',display:'flex',flexDirection:'column',gap}}>{children}</div>);
const Toggle2 = ({on}) => (<span style={{width:30,height:18,borderRadius:99,background:on?'var(--accent)':'var(--border-2)',position:'relative',display:'inline-block',flex:'0 0 auto'}}><span style={{position:'absolute',top:2,left:on?14:2,width:14,height:14,borderRadius:99,background:'#fff',boxShadow:'0 1px 2px rgba(0,0,0,.15)'}}/></span>);
const Seg = ({options,activeIdx=0}) => (<div style={{display:'inline-flex',padding:3,gap:2,background:'var(--bg-raised)',border:'1px solid var(--border-1)',borderRadius:7,flexWrap:'wrap'}}>{options.map((o,i)=>{const a=i===activeIdx;return <div key={o} style={{padding:'5px 12px',borderRadius:5,cursor:'pointer',background:a?'var(--bg-surface)':'transparent',boxShadow:a?'0 0 0 1px var(--border-1)':'none',color:a?'var(--ink-1)':'var(--ink-3)',fontSize:12,fontWeight:a?600:500}}>{o}</div>;})}</div>);
const SetRow = ({title,sub,children}) => (<div style={{display:'grid',gridTemplateColumns:'260px 1fr',gap:12,padding:'13px 16px',alignItems:'center',borderTop:'1px solid var(--border-1)'}}><div><div style={{fontSize:12.5,fontWeight:500,color:'var(--ink-1)'}}>{title}</div><div style={{marginTop:2,fontSize:11.5,color:'var(--ink-3)'}}>{sub}</div></div><div style={{display:'flex',justifyContent:'flex-end'}}>{children}</div></div>);
const Gate = ({ok,label,sub}) => (<div style={{borderRadius:10,border:'1px solid color-mix(in oklab, '+(ok?'var(--exact)':'var(--fuzzy)')+' 40%, var(--border-1))',background:'color-mix(in oklab, '+(ok?'var(--exact)':'var(--fuzzy)')+' 7%, var(--bg-surface))',padding:'14px 16px',display:'flex',alignItems:'center',gap:12}}><div style={{width:30,height:30,borderRadius:7,flex:'0 0 auto',background:'color-mix(in oklab, '+(ok?'var(--exact)':'var(--fuzzy)')+' 18%, var(--bg-surface))',color:ok?'var(--exact)':'var(--fuzzy)',display:'grid',placeItems:'center'}}><Icon name={ok?'checkCircle':'alert'} size={15}/></div><div style={{flex:1}}><div style={{fontSize:13.5,fontWeight:600,color:'var(--ink-1)'}}>{label}</div><div style={{marginTop:2,fontSize:12,color:'var(--ink-3)'}}>{sub}</div></div></div>);
const Tree = ({rows}) => (<div className="mono" style={{fontSize:11.5,lineHeight:1.9,color:'var(--ink-2)'}}>{rows.map((r,i)=>(<div key={i} style={{display:'flex',alignItems:'center',gap:8,paddingLeft:(r.d||0)*18}}>{r.dir?<Icon name="folder" size={12} style={{color:'var(--accent)'}}/>:<Icon name="file" size={12} style={{color:'var(--ink-4)'}}/>}<span style={{color:r.dir?'var(--ink-1)':'var(--ink-2)',fontWeight:r.dir?600:400}}>{r.name}</span><span style={{flex:1}}/>{r.meta?<span style={{color:'var(--ink-4)',fontSize:10.5}}>{r.meta}</span>:null}</div>))}</div>);

const PPMain = () => (<Body>
 <Gate ok={true} label="Proof pack assembled · 387 pages" sub="Page images + proofer text + illustrations + project metadata, bundled in the layout PGDP expects." />
 <div style={{display:'flex',gap:12}}><Stat label="pages" value="387" tone="exact"/><Stat label="text files" value="387"/><Stat label="illustrations" value="54" tone="ocr"/><Stat label="bundle size" value="1.4 GB"/></div>
 <Card title="Contents" sub="What gets bundled into the proof pack" right={<Button variant="default" size="sm" icon="eye">Preview file</Button>}><Tree rows={PP_TREE}/></Card>
 <Card title="Per-page completeness" sub="Every page must carry both an image and a text file"><div style={{display:'flex',alignItems:'center',gap:14}}><div style={{flex:1,height:8,borderRadius:99,background:'var(--bg-sunk)',overflow:'hidden'}}><div style={{width:'100%',height:'100%',background:'var(--exact)'}}/></div><span className="mono" style={{fontSize:12,fontWeight:600,color:'var(--exact)'}}>387 / 387</span></div></Card>
</Body>);
const PPSettings = () => (<Body><div><h2 style={{fontSize:16,fontWeight:600,color:'var(--ink-1)'}}>Stage settings · Proof pack</h2><div style={{marginTop:3,fontSize:12,color:'var(--ink-3)'}}>What to include and how files are named.</div></div>
 <Card><SetRow title="Include page images" sub="Bilevel page PNGs"><Toggle2 on={true}/></SetRow><SetRow title="Include proofer text" sub="Per-page UTF-8 with markup"><Toggle2 on={true}/></SetRow><SetRow title="Include illustration crops" sub="Extracted at stage 17"><Toggle2 on={true}/></SetRow><SetRow title="File naming" sub="Page file naming scheme"><Seg options={['page0001','0001','p001']} activeIdx={0}/></SetRow><SetRow title="Text encoding" sub="Output text encoding"><Seg options={['UTF-8','Latin-1']} activeIdx={0}/></SetRow><SetRow title="Re-assemble pack" sub="Rebuild from current stage outputs"><Button variant="default" size="sm" icon="refresh">Re-assemble</Button></SetRow></Card></Body>);
Object.assign(window,{PPMain,PPSettings});
